name: HardcoreZombies
version: '${version}'

main: me.suxuan.hardcorezombies.HardcoreZombies
api-version: '1.21'
authors:
  - SuXuan_Dev
description: A hardcore zombies minigame plugin utilizing Paper Components and PDC.
depend: [ SlimeArenaAPI ]

load: POSTWORLD
commands:
  hzombies:
    description: 僵尸模式主命令
    aliases: [ hz ]

permissions:
  hardcorezombies.admin:
    description: 创建/销毁房间、强制开始、配置刷怪点
    default: op
  hardcorezombies.play:
    description: 加入、离开、查看房间列表
    default: true